// Generated by CoffeeScript 2.6.1
(function () {
	/*
  SPDX-License-Identifier: MIT
  Author: Mark Gutenberger <mark-gutenberger@outlook.com>
  stream.coffee (c) 2022
  Desc: description
  Created:  2022-03-04T14:13:06.709Z
  Modified: 2022-03-11T00:28:36.263Z
  */
	var STREAM;

	STREAM = (socket) => {
		return function () {
			socket.on(
				'subscribe',
				(data) => {
					return function () {};
					// subscribe/join a room
				},
				socket.join(data.room).join(data.socketId)
			);
			//endfunc
			socket.on(
				'newUserStart',
				(data) => {
					return function () {};
				},
				socket.to(data.to).emit('newUserStart', {
					sender: data.sender,
				})
			);
			socket.on(
				'sdp',
				(data) => {
					return function () {};
				},
				socket.to(data.to).emit('sdp', {
					description: data.description,
					sender: data.sender,
				})
			);
			socket.on(
				'ice candidates',
				(data) => {
					return function () {};
				},
				socket.to(data.to).emit('ice candidates', {
					candidate: data.candidate,
					sender: data.sender,
				})
			);
			//endfunc
			return socket.on(
				'chat',
				(data) => {},
				socket.to(data.room).emit('chat', {
					sender: data.sender,
					msg: data.msg,
				})
			);
		};
	};

	//endfunc
	module.exports = STREAM;
}.call(this));

//# sourceMappingURL=stream.js.map
